name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app/backend
            docker-compose pull
            docker-compose up -d
